version: '3.8'

services:
  mateboard:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - DATABASE_PATH=./data/db.sqlite
    volumes:
      - mateboard_data:/app/data

volumes:
  mateboard_data: