version: '3.8'

services:
  mateboard:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
    volumes:
      - ./db.sqlite:/app/db.sqlite