import type { Metadata } from "next";
import "./globals.css";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{ minHeight: "100vh" }}
        className="bg-[#f0f8f0] font-mono min-h-screen"
      >
        <Header />
        <div className="max-w-6xl my-4 md:my-8 mx-auto min-h-[calc(100vh-212px)] md:px-0 px-4">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
